const NAME_SPACE = 'ellamd';

export const GET_FORMULATIONS_REQUEST = `${NAME_SPACE}/GET_FORMULATIONS_REQUEST`;
export const GET_FORMULATIONS_SUCCESS = `${NAME_SPACE}/GET_FORMULATIONS_SUCCESS`;
export const GET_FORMULATIONS_ERROR = `${NAME_SPACE}/GET_FORMULATIONS_ERROR`;

export const GET_INGREDIENTS = `${NAME_SPACE}/GET_INGREDIENTS`;

export default {
	GET_FORMULATIONS_REQUEST,
	GET_FORMULATIONS_SUCCESS,
	GET_FORMULATIONS_ERROR,
	GET_INGREDIENTS
};
